# Docker Compose documentation: https://docs.docker.com/compose/
version: "3"

# Enapter Gateway supports custom services via Docker Compose. Below is an example of how to run
# custom software on the gateway.
#
# To run Grafana® on Enapter Gateway, uncomment the config below by removing the `#` symbol starting
# from the services: line.
#
# It's already configured with the Enapter datasource plugin, so no further configuration is needed.
# Grafana will be available on port :3000 on the gateway, e.g., http://enapter-gateway.local:3000.
#
# The default login credentials are admin/admin. Be sure to change the default password to mitigate
# security risks.
#
# Enapter datasource documentation: https://go.enapter.com/grafana-docs
#
# Run `systemctl restart enapter-docker-compose` after updating this file.
#
# The Grafana Labs Marks are trademarks of Grafana Labs, and are used with Grafana Labs' permission.
# We are not affiliated with, endorsed or sponsored by Grafana Labs or its affiliates.
#
#services:
#  grafana:
#    image: enapter/grafana-plugins
#    user: root
#    ports:
#      - 0.0.0.0:3000:3000
#    env_file: /user/etc/enapter/enapter-token.env
#    environment:
#      - ENAPTER_API_URL=http://10.88.0.1/api
#      - PROVISION_ENAPTER_BUILT_IN_DASHBOARDS=1
#      # NOTE: Gateway 3.0 does not support Commands Plugin yet, but it's on the way.
#      - DISABLE_ENAPTER_COMMANDS_PANEL_PLUGIN=1
#    volumes:
#      - /user/grafana-data:/var/lib/grafana
