#!/bin/sh
# SPDX-FileCopyrightText: 2023 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

. /usr/share/scripts/enapter-variables

user_disk_type="auto"
disk_opts="defaults,rw,nodev,nosuid"

# create mountpoint if not exists
test -d "$user_fs_mount" || mkdir -p "$user_fs_mount"

mount "$hdd_data_device" -t "$user_disk_type" -o "$disk_opts" "$user_fs_mount"

touch "$user_fs_mount/it_works"

cp /proc/vmcore "$user_fs_mount/dump"

sync; sync; sync

umount "$user_fs_mount"

reboot -f
