#!/bin/sh
# SPDX-FileCopyrightText: 2023 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

passwordreset_enabled() {
  if [ -z ${bootparam_do_password_reset} ]; then
    return 1
  fi
  return 0
}

passwordreset_run() {
    local userspace_label="enp-data-disk"
    local userspace_device="/dev/disk/by-label/$userspace_label"
    local userspace_mountdir="/user"
    local password_file="/etc/enapter/enapter-superuser-password.env"
    local disk_opts="defaults,rw,nodev,nosuid"

    if [ -L ${userspace_device} ]; then
      mkdir -p $userspace_mountdir
      mount "$userspace_device" -t auto -o "$disk_opts" "$userspace_mountdir" || fatal "Failed to mount userspace disk"
      rm -f "$userspace_mountdir$password_file"
      sync; sync; sync
      umount $userspace_mountdir || fatal "Failed to unmount userspace disk"
      info "Password reset done"
    else
      info "No userspace disk found, nothing to reset"
    fi

    sleep 3
}
