#!/bin/sh
# SPDX-FileCopyrightText: 2023 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

. /usr/share/scripts/enapter-variables

ensure_sync() {
  sync; sync; sync
}

passwordreset_enabled() {
  if [ -z ${bootparam_do_password_reset} ]; then
    return 1
  fi
  return 0
}

passwordreset_run() {
    local disk_opts="defaults,rw,nodev,nosuid"

    if [ -L ${hdd_data_device} ]; then
      mkdir -p $user_fs_mount
      mount "$hdd_data_device" -t auto -o "$disk_opts" "$user_fs_mount" || fatal "Failed to mount userspace disk"
      rm -f "$user_fs_mount$etc_enapter/$enapter_superuser_password_env_file"
      ensure_sync
      umount $user_fs_mount || fatal "Failed to unmount userspace disk"
      info "Password reset done"
    else
      info "No userspace disk found, nothing to reset"
    fi

    sleep 3
}
