# Helper shell variables
#
# SPDX-FileCopyrightText: 2024 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

rootfs_patch_script="patch_rootfs.sh"

disk_boot_label="enp-os"
disk_data_label="enp-data-disk"
disk_data_reset_label="enp-data-reset"
disk_recovery_label="enp-recovery"
disk_images_label="enp-images"
disk_usb_boot_label="enp-os-usb"
disk_export_label="enp-export"

boot_mount="/boot"
hdd_boot_mount="/mnt/boot"
root_ro_mount="/overlay_ro"
root_rw_mount="/overlay_rw"
user_fs_mount="/user"
recovery_mount="/recovery"
export_mount="/export"
root_mount="/"
images_mount="$user_fs_mount/images"
overlay_images_mount="/overlay-images"
overlay_layers_mount="/overlay-layers"
overlay_images_lock="$overlay_images_mount/images.lock"
overlay_layers_lock="$overlay_layers_mount/layers.lock"
enapter_superuser_password_env_file="enapter-superuser-password.env"
etc_enapter="/etc/enapter"
user_etc_enapter="$user_fs_mount$etc_enapter"
rwfs_file="rwfs"
user_rwfs_file="$user_etc_enapter/$rwfs_file"
user_enapter_authorized_keys="$user_etc_enapter/authorized_keys"
enapter_authorized_keys="/home/enapter/.ssh/authorized_keys"
layers_ro_mount_base_dir="/layers"
overlayfs_upperdir="$root_rw_mount/upperdir"
overlayfs_workdir="$root_rw_mount/work"
efi_enapter_dir="EFI/enapter"
efi_boot_dir="EFI/BOOT"
efi_enapter="$root_mount$efi_enapter_dir"
efi_boot="$root_mount$efi_boot_dir"

usb_boot_device="/dev/disk/by-label/$disk_usb_boot_label"
hdd_boot_device="/dev/disk/by-label/$disk_boot_label"
hdd_data_device="/dev/disk/by-label/$disk_data_label"
hdd_data_reset_device="/dev/disk/by-label/$disk_data_reset_label"
hdd_recovery_device="/dev/disk/by-label/$disk_recovery_label"
hdd_export_device="/dev/disk/by-label/$disk_export_label"
hdd_images_device="/dev/disk/by-label/$disk_images_label"

grubenv_path="$boot_mount/EFI/BOOT/grubenv"
network_config_file="network.yaml"

netplan_config_dir="/etc/netplan"
netplan_bin="/usr/sbin/netplan"

docker_compose_dir="etc/docker-compose"
docker_compose_images_dir="$docker_compose_dir/images"
docker_compose_file="$docker_compose_dir/docker-compose.yml"
docker_compose_images_readme_file="$docker_compose_images_dir/readme.txt"
